[env:esp32-2432S028R]
platform = espressif32@6.10.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags =
  -std=gnu++17

lib_deps =
  lovyan03/LovyanGFX@^1.2.7
